apiVersion: skaffold/v4beta10
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: cuevasgpablo/auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: cuevasgpablo/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
          - src: '**/*.vue'
            dest: .

    - image: cuevasgpablo/tickets
      context: tickets
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: cuevasgpablo/orders
      context: orders
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: cuevasgpablo/expiration
      context: expiration
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: cuevasgpablo/payments
      context: payments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
