name: deploy-payments

on:
  push:
    branches:
      - main
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        
      - 
        name: Build Docker Image
        run: cd payments && docker build -t cuevasgpablo/payments .
        
      - 
        name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      - 
        name: Push Docker Image
        run: docker push cuevasgpablo/payments

      - 
        name: Config DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      -
        name: Set DigitalOcean Kubernetes Cluster
        run: doctl kubernetes cluster kubeconfig save ticketing

      -
        name: Restart payments deployment
        run: kubectl rollout restart deployment payments-depl
