name: deploy-tickets

on:
  push:
    branches:
      - main
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        
      - 
        name: Build Docker Image
        run: cd tickets && docker build -t cuevasgpablo/tickets .
        
      - 
        name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      - 
        name: Push Docker Image
        run: docker push cuevasgpablo/tickets

      - 
        name: Config DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      -
        name: Set DigitalOcean Kubernetes Cluster
        run: doctl kubernetes cluster kubeconfig save ticketing

      -
        name: Restart tickets deployment
        run: kubectl rollout restart deployment tickets-depl
